from trello import TrelloBase as TrelloBase
from trello.compat import force_str as force_str
from typing import Any, Optional, List, Dict

class Checklist(TrelloBase):
    client: Any = ...
    trello_card: Any = ...
    id: Any = ...
    name: Any = ...
    items: List[Dict] = ...
    def __init__(
        self,
        client: Any,
        checked: Any,
        obj: Any,
        trello_card: Optional[Any] = ...,
    ): ...
    def add_checklist_item(self, name: Any, checked: bool = ...): ...
    def delete_checklist_item(self, name: Any) -> None: ...
    def clear(self) -> None: ...
    def set_checklist_item(self, name: Any, checked: Any): ...
    def rename(self, new_name: Any): ...
    def rename_checklist_item(self, name: Any, new_name: Any): ...
    def delete(self) -> None: ...
